"""new column status added

Revision ID: 50388787dc44
Revises: 92162d04ab6d
Create Date: 2021-03-05 16:46:55.677694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50388787dc44'
down_revision = '92162d04ab6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
