"""Adding column category

Revision ID: 92162d04ab6d
Revises: 
Create Date: 2021-03-04 10:58:43.245008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92162d04ab6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('category', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'category')
    # ### end Alembic commands ###
