"""added new column

Revision ID: a386880b7028
Revises: 50388787dc44
Create Date: 2021-03-08 14:28:00.338746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a386880b7028'
down_revision = '50388787dc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserved_username', sa.Column('linked_to', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserved_username', 'linked_to')
    # ### end Alembic commands ###
